CREATE DATABASE IF NOT EXISTS clients_db;

USE clients_db;

CREATE TABLE IF NOT EXISTS clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    dni VARCHAR(20) NOT NULL UNIQUE,
    gender VARCHAR(10),
    age INTEGER UNSIGNED,
    address VARCHAR(100),
    phone VARCHAR(20),
    password VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);